### ISSUE TITLE
Define the API endpoints of the simulator:

### ISSUE THREAD

**Issue by mortenskoett** [mortenskoett/itu-devops-group-noname#18]
1. What paths will be called
2. What logic happens
3. What is returned

**Comment by mortenskoett** [comment]
Lad os lige snakke sammen, naar du har mapped end points og inden du implementerer noget. Det ser ud til lige nu ifbm. refactor af server.js, at vi ikke behoever et dedikeret simulator api, men vi kan bruge det samme api til baade vores egne kald og apiet... Lidt afhaengig af hvor weird simulator apiet ser ud.

**Comment by embu97** [comment]
Can this issue be closed?
