### ISSUE TITLE
Add 'my timeline' + 'public timeline'. Requires rerouting and UI items.

### ISSUE THREAD

**Issue by mortenskoett** [mortenskoett/itu-devops-group-noname#20]

**Comment by embu97** [comment]
I have just rerouted the "Minitwit" to /public and added "Home" when logged in, which routes to /home. Is this it?

**Comment by mortenskoett** [comment]
So the functionality is now
- clicking minitwit word takes the user to the public tweet list? 
- when logged in a button is shown taking the user to her private tweet list?

Sounds about right to me.
