### ISSUE TITLE
Write a SLA for our API

### ISSUE THREAD

**Issue by dkfrankandersen** [mortenskoett/itu-devops-group-noname#68]

**Comment by Durix** [comment]
Hello.
This is Philip from group i (TB)
We have yet to recieve your SLA and as such cannot start monitoring you as we have no metrics to keep tabs on.
We hope to hear from you soon.
Sincerely Philip from group i (TB)

**Comment by dkfrankandersen** [comment]
> Hello.
> This is Philip from group i (TB)
> We have yet to recieve your SLA and as such cannot start monitoring you as we have no metrics to keep tabs on.
> We hope to hear from you soon.
> Sincerely Philip from group i (TB)

Philip without leaving more information about your self I dont know how to get in touch..

**Comment by dkfrankandersen** [comment]
The SLA is available here: https://github.com/mortenskoett/itu-devops-group-noname/blob/SLA-v1/DevOps%20Group%20J%20-%20SLA.pdf
